server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
appDescription: "reto Powerup"
appVersion: "1.0.0"
